name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: install coverage tool
      run: |
        sudo apt-get update
        sudo apt-get install -y gcovr
        
    - name: build sender
      run: g++ -Wall -Wextra -fprofile-arcs Battery_Charging_Parameter_Main.cpp Battery_Charging_Parameter.cpp -o sender 

    - name: build test sender battery parameters
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage test_Battery_Charging_Parameter.cpp Battery_Charging_Parameter.cpp -o testchecker

    - name: build receiver
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage -o receiver Receiver/*.c
      
    - name: run sender
      run: ./sender

    - name: run testchecker
      run: ./testchecker

    - name: run help
      run: ./receiver
      
    - name: run receiver test
      run: ./receiver -t
      
    - name: run receiver application
      run: ./receiver -r
      
    - name: collect coverage
      run: gcovr --gcov-exclude=".*test.*" -r . --html --html-details -o coverage.html --print-summary

    - name: create coverage artifact
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: ./*.html
        retention-days: 21
